### ISSUE TITLE
"Books with archive.org"

### ISSUE THREAD

**Issue by greencardamom** [internetarchive/ware#27]
This doesn't sound right somehow. Maybe "Books at archive.org" .. trying to keep short! Also there is the difference between books and journal articles (any "book" with an ID that starts with "sim_") in which case "Books at archive.org" and "Journals at archive.org"

**Comment by markjohngraham** [comment]
I was very clear: https://internetarchive.slack.com/archives/C04PLJVSPAP/p1680718855465209

- Mark

**Comment by greencardamom** [comment]
I see, missed that, that is better. Will close.
